# 1. Fizz Buzz
# Write a program that prints the numbers from 1 to 100. 
# But for multiples of three print "Fizz" instead of the number and for the multiples of five print "Buzz". 
# For numbers which are multiples of both three and five print "FizzBuzz".
Link to leetcode: https://leetcode.com/problems/fizz-buzz/
2. Sum of All Multiples of 3 or 5 below 1000
# If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
# Find the sum of all the multiples of 3 or 5 below 1000.
3. Fibonacci Sequence
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Dillon Stone-Miller DiR solution

# index = 1
# for i in range(1,101):
#     if index % 3 == 0 and index % 5 == 0:
#         print(f'{index}: FizzBuzz \n')
#     elif index % 3 == 0:
#         print(f'{index}: Fizz \n')
#     elif index % 5 == 0:
#         print(f'{index}: Buzz \n')
#     else:
#         print(index)
#     index += 1

# experiments
for i in range(1,100):
    print (i)
